#!/usr/bin/make
#
# $Id: Makefile,v 1.5 2002-06-20 13:16:57 sian Exp $
#
.PHONY : install

all : reset.a68 ca68
	echo "Nothing to be done for all"

install :
	$(INSTALLPROG) -p reset.a68 ca68 $(BINDIR)
