#!/usr/bin/make
#
# $Id: Makefile,v 1.5.2.1 2004/09/04 17:36:16 teshields Exp $
#
.PHONY : install

all : reset.a68 ca68
	echo "Nothing to be done for all"

install :
	$(INSTALLPROG) -p reset.a68 ca68 $(BINDIR)
