#!/bin/sh
# Executes mm.bin with a system-wide command file

if [ ! -x /usr/local/bin/mm.bin ]
then echo "Cannot find mm.bin"
else
   /usr/local/bin/mm.bin -i /usr/local/share/algol68toc/cmds.eli "$@"
fi

# end of mm
